# Form implementation generated from reading ui file 'despedir.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 60, 301, 291))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 20, 131, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(560, 120, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 180, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(550, 240, 111, 16))
        self.label_4.setObjectName("label_4")
        self.Nombre = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Nombre.setGeometry(QtCore.QRect(550, 150, 151, 22))
        self.Nombre.setObjectName("Nombre")
        self.rut = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.rut.setGeometry(QtCore.QRect(550, 210, 141, 22))
        self.rut.setObjectName("Rut")
        self.codigo_E = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.codigo_E.setGeometry(QtCore.QRect(550, 270, 141, 22))
        self.codigo_E.setObjectName("codigo_E")
        self.Buscar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Buscar.setGeometry(QtCore.QRect(550, 340, 93, 28))
        self.Buscar.setObjectName("Buscar")
        self.borrar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.borrar.setGeometry(QtCore.QRect(110, 400, 93, 28))
        self.borrar.setObjectName("Borrar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Desvincular trabajador", "Desvincular trabajador"))
        self.label.setText(_translate("MainWindow", "Desvincular socio"))
        self.label_2.setText(_translate("MainWindow", "Nombre"))
        self.label_3.setText(_translate("MainWindow", "Rut"))
        self.label_4.setText(_translate("MainWindow", "Codigo empleado"))
        self.Buscar.setText(_translate("MainWindow", "Buscar"))
        self.borrar.setText(_translate("MainWindow", "Desvincular"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
